
// ######### authentication #########
export const  RESET_PASSWORD = "RESET_PASSWORD";
export const  LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const  LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const  LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';    
export const    LOGOUT = 'USERS_LOGOUT';

// ######### send quick sms #########
export const SEND_SMS_SUCCESS ="SEND_SMS_SUCCESS";
export const SEND_SMS_FAILURE ="SEND_SMS_FAILURE"

// ######### dashoard #########
export const GET_SMS_SUCCESS = "GET_SMS_SUCCESS";
export const GET_SMS_FAILURE = "GET_SMS_FAILURE";

// ######### Main contacts #########
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_FAILURE = "GET_CONTACT_FAILURE";
export const EDIT_CONTACT_SUCCESS  = "EDIT_CONTACT_SUCCESS" ;
export const EDIT_CONTACT_FAILURE  =  "EDIT_CONTACT_FAILURE";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_FAILURE = "ADD_CONTACT_FAILURE";
export const DELETE_CONTACT_SUCCESS =  "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAILURE =  "DELETE_CONTACT_FAILURE";

// ######### Sub contacts #########
export const GET_CONTACT_DETAILS_SUCCESS = "GET_CONTACT_DETAILS_SUCCESS";
export const GET_CONTACT_DETAILS_FAILURE = "GET_CONTACT_DETAILS_FAILURE";
export const SUB_EDIT_CONTACT_SUCCESS = "SUB_EDIT_CONTACT_SUCCESS";
export const SUB_EDIT_CONTACT_FAILURE = "SUB_EDIT_CONTACT_FAILURE";
export const SUB_ADD_CONTACT_SUCCESS = "SUB_ADD_CONTACT_SUCCESS";
export const SUB_ADD_CONTACT_FAILURE = "SUB_ADD_CONTACT_FAILURE";
export const SUB_DELETE_CONTACT_SUCCESS = "SUB_DELETE_CONTACT_SUCCESS";
export const SUB_DELETE_CONTACT_FAILURE = "SUB_DELETE_CONTACT_FAILURE";

// ######### campaigns #########
export const GET_CAMPAIGNS_SUCCESS = "GET_CAMPAIGNS_SUCCESS";
export const GET_CAMPAIGNS_FAILURE = "GET_CAMPAIGNS_FAILURE";
export const EDIT_CAMPAIGNS_SUCCESS = "EDIT_CAMPAIGNS_SUCCESS";
export const EDIT_CAMPAIGNS_FAILURE = "EDIT_CAMPAIGNS_FAILURE";

// ######### users #########
export const GET_SUPERUSER_SUCCESS = "GET_SUPERUSER_SUCCESS";
export const GET_SUPERUSER_FAILURE = "GET_SUPERUSER_FAILURE";

export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS";
export const GET_ADMIN_FAILURE = "GET_ADMIN_FAILURE";

export const GET_MANAGERS_SUCCESS = "GET_MANAGERS_SUCCESS";
export const GET_MANAGERS_FAILURE = "GET_MANAGERS_FAILURE";


// ######### accounts #########
export const ADD_ACCOUNTS_SUCCESS = "ADD_ACCOUNTS_SUCCESS";
export const ADD_ACCOUNTS_FAILURE = "ADD_ACCOUNTS_FAILURE";

export const GET_ACCOUNTS_SUCCESS = "GET_ACCOUNTS_SUCCESS";
export const GET_ACCOUNTS_FAILURE = "GET_ACCOUNTS_FAILURE";

export const EDIT_ACCOUNT_SUCCESS = "EDIT_ACCOUNT_SUCCESS";
export const EDIT_ACCOUNT_FAILURE = "EDIT_ACCOUNT_FAILURE";

export const DELETE_ACCOUNT_SUCCESS =  "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAILURE =  "DELETE_ACCOUNT_FAILURE";

export const DEPOSIT_CREDIT_SUCCESS = "DEPOSIT_CREDIT_SUCCESS";
export const DEPOSIT_CREDIT_FAILURE = "DEPOSIT_CREDIT_FAILURE";

export const DEPOSIT_HISTORY_SUCCESS = "DEPOSIT_HISTORY_SUCCESS";
export const DEPOSIT_HISTORY_FAILURE = "DEPOSIT_HISTORY_FAILURE";