
export const  RESET_PASSWORD = "RESET_PASSWORD";
export const  LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const  LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const  LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';
    
export const    LOGOUT = 'USERS_LOGOUT';

export const SEND_SMS_SUCCESS ="SEND_SMS_SUCCESS";
export const SEND_SMS_FAILURE ="SEND_SMS_FAILURE"

export const GET_SMS_SUCCESS = "GET_SMS_SUCCESS";
export const GET_SMS_FAILURE = "GET_SMS_FAILURE";

export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_FAILURE = "GET_CONTACT_FAILURE";
export const GET_CONTACT_DETAILS_SUCCESS = "GET_CONTACT_DETAILS_SUCCESS";
export const GET_CONTACT_DETAILS_FAILURE = "GET_CONTACT_DETAILS_FAILURE";

export const GET_ACCOUNTS_SUCCESS = "GET_ACCOUNTS_SUCCESS";
export const GET_ACCOUNTS_FAILURE = "GET_ACCOUNTS_FAILURE";
export const EDIT_ACCOUNT_SUCCESS = "EDIT_ACCOUNT_SUCCESS";
export const EDIT_ACCOUNT_FAILURE = "EDIT_ACCOUNT_FAILURE";
export const DEPOSIT_CREDIT_SUCCESS = "DEPOSIT_CREDIT_SUCCESS";
export const DEPOSIT_CREDIT_FAILURE = "DEPOSIT_CREDIT_FAILURE";
export const DEPOSIT_HISTORY_SUCCESS = "DEPOSIT_HISTORY_SUCCESS";
export const DEPOSIT_HISTORY_FAILURE = "DEPOSIT_HISTORY_FAILURE";